spring:
  datasource:
    url: ${db_url}
    username: ${db_user}
    password: ${db_pass}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
